
--Assign permissions
REVOKE CREATE ON SCHEMA public FROM dd_ui;
REVOKE CREATE ON SCHEMA public FROM dd_ui_app;

GRANT USAGE ON SCHEMA dd_ui TO dd_ui;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dd_ui TO dd_ui;
ALTER DEFAULT PRIVILEGES IN SCHEMA dd_ui GRANT EXECUTE ON FUNCTIONS TO dd_ui;

GRANT SELECT ON TABLE pg_catalog.pg_extension TO dd_ui;
